/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package brawlmula;

import java.awt.Color;

/**
 *
 * @author ndufour
 */
public class MainMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenu.class.getName());

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        
        setSize(1280, 760); 
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnCommencer = new javax.swing.JButton();
        btnReglages1 = new javax.swing.JButton();
        btnQuitter = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brawlmula/INTERFACE/Titre.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 250));

        btnCommencer.setFont(new java.awt.Font("Alegreya Sans SC", 1, 48)); // NOI18N
        btnCommencer.setText("[ Commencer Jouer ]");
        btnCommencer.setToolTipText("");
        btnCommencer.setBorderPainted(false);
        btnCommencer.setContentAreaFilled(false);
        btnCommencer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCommencer.setFocusPainted(false);
        btnCommencer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCommencerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCommencerMouseExited(evt);
            }
        });
        btnCommencer.addActionListener(this::btnCommencerActionPerformed);
        getContentPane().add(btnCommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 440, 60));

        btnReglages1.setFont(new java.awt.Font("Alegreya Sans SC", 1, 48)); // NOI18N
        btnReglages1.setText("[ Réglages ]");
        btnReglages1.setToolTipText("");
        btnReglages1.setBorderPainted(false);
        btnReglages1.setContentAreaFilled(false);
        btnReglages1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReglages1.setFocusPainted(false);
        btnReglages1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReglages1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReglages1MouseExited(evt);
            }
        });
        btnReglages1.addActionListener(this::btnReglages1ActionPerformed);
        getContentPane().add(btnReglages1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, -1, 60));

        btnQuitter.setFont(new java.awt.Font("Alegreya Sans SC", 1, 48)); // NOI18N
        btnQuitter.setText("[ Quitter ]");
        btnQuitter.setToolTipText("");
        btnQuitter.setBorderPainted(false);
        btnQuitter.setContentAreaFilled(false);
        btnQuitter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuitter.setFocusPainted(false);
        btnQuitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuitterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuitterMouseExited(evt);
            }
        });
        btnQuitter.addActionListener(this::btnQuitterActionPerformed);
        getContentPane().add(btnQuitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 640, 240, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brawlmula/INTERFACE/acceuil.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommencerActionPerformed
        Selection selection = new Selection();
        selection.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCommencerActionPerformed

    private void btnCommencerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCommencerMouseEntered
        btnCommencer.setForeground(new Color(255, 215, 0));
        
        btnCommencer.setOpaque(true);
    
        btnCommencer.setBackground(new Color(255, 245, 180)); 
        btnCommencer.setForeground(new Color(180, 40, 20));
    }//GEN-LAST:event_btnCommencerMouseEntered

    private void btnCommencerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCommencerMouseExited
        btnCommencer.setForeground(new Color(110, 25, 25));
        
        btnCommencer.setOpaque(false);
        btnCommencer.setForeground(new Color(110, 25, 25));
    }//GEN-LAST:event_btnCommencerMouseExited

    private void btnQuitterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitterMouseEntered
        btnQuitter.setForeground(new Color(255, 215, 0));
        
        btnQuitter.setOpaque(true);
    
        btnQuitter.setBackground(new Color(255, 245, 180)); 
        btnQuitter.setForeground(new Color(180, 40, 20));
    }//GEN-LAST:event_btnQuitterMouseEntered

    private void btnQuitterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitterMouseExited
        btnQuitter.setForeground(new Color(110, 25, 25));
        
        btnQuitter.setOpaque(false);
        btnQuitter.setForeground(new Color(110, 25, 25));
    }//GEN-LAST:event_btnQuitterMouseExited

    private void btnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterActionPerformed
        int choix = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Veux-tu vraiment quitter le jeu ?",
        "Quitter",
        javax.swing.JOptionPane.YES_NO_OPTION,
        javax.swing.JOptionPane.QUESTION_MESSAGE
    );

    if (choix == javax.swing.JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_btnQuitterActionPerformed

    private void btnReglages1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReglages1MouseEntered
        btnReglages1.setForeground(new Color(255, 215, 0));
        
        btnReglages1.setOpaque(true);
    
        btnReglages1.setBackground(new Color(255, 245, 180)); 
        btnReglages1.setForeground(new Color(180, 40, 20));
    }//GEN-LAST:event_btnReglages1MouseEntered

    private void btnReglages1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReglages1MouseExited
        btnReglages1.setForeground(new Color(110, 25, 25));
        
        btnReglages1.setOpaque(false);
        btnReglages1.setForeground(new Color(110, 25, 25));
    }//GEN-LAST:event_btnReglages1MouseExited

    private void btnReglages1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReglages1ActionPerformed
        Reglages selection = new Reglages();
        selection.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReglages1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCommencer;
    private javax.swing.JButton btnQuitter;
    private javax.swing.JButton btnReglages1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
